//FETCHING REQUEST ACTION TYPES
export const actionTypes = {
    FETCH_CATEGORY_CURRENCY_REQUEST : "FETCH_CATEGORY_CURRENCY_REQUEST",
    FETCH_CATEGORY_CURRENCY_SUCCESS : "FETCH_CATEGORY_CURRENCY_SUCCESS",
    FETCH_CATEGORY_CURRENCY_FAILURE : "FETCH_CATEGORY_CURRENCY_FAILURE",
    ADD_T0_CART:"ADD_T0_CART",
    CATEGORY_FILTER: "CATEGORY_FILTER",
    CHOOSED_CURRENCY: "CHOOSED_CURRENCY",
    INCREASE_CART_PRODUCT_COUNT: "INCREASE_CART_PRODUCT_COUNT",
    DECREASE_CART_PRODUCT_COUNT: "DECREASE_CART_PRODUCT_COUNT",
    SELECT_PRODUCT_OPTIONS_AT_CART: "SELECT_PRODUCT_OPTIONS_AT_CART",
    CART_NEXT_SLIDER_BTN: "CART_NEXT_SLIDER_BTN",
    CART_PREVIOUS_SLIDER_BTN: "CART_PREVIOUS_SLIDER_BTN"
}

